name: christ_connect
description: Christ Connect — Bible + Worship App
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  cloud_firestore: ^5.1.0
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  youtube_player_flutter: ^8.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
